# Server port configuration
server.port=8080
spring.application.name=currency-converter

# External API Setup
# In EKS, the External Secrets Manager will inject the 'CURRENCY_API_KEY' environment variable.
# The ':mock-key-for-local' part ensures the app still boots up locally if the env var is missing.

currency.api.key=${CURRENCY_API_KEY:mock-key-for-local}
currency.api.url=https://v6.exchangerate-api.com/v6/{key}/pair/{from}/{to}/{amount}